replicaCount: 1
image:
  repository: dimozone/vehicle-info-web
  pullPolicy: IfNotPresent
  tag: bcaafab
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
env:
  NODE_ENV: dev
  PORT: '8080'
  LOG_LEVEL: info
  DIMO_IDENTITY_API: https://identity-api.dev.dimo.zone/query
  DEVICE_DEFINITIONS_API_URL: https://device-definitions-api.dev.dimo.zone/device-definitions/autocomplete
service:
  type: ClusterIP
  ports:
    http:
      port: 8080
      targetPort: http
      protocol: TCP
ports:
  - name: http
    containerPort: 8080
    protocol: TCP
ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    external-dns.alpha.kubernetes.io/hostname: sharemyride.dev.drivedimo.com
  hosts:
    - host: sharemyride.dev.drivedimo.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
