replicaCount: 1
image:
  repository: dimozone/vehicle-info-web
  pullPolicy: IfNotPresent
  tag: efc8ee3
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
env:
  ENVIRONMENT: dev
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: devices_api
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  SERVICE_NAME: vehicle-info-web
  DIMO_API_BASEURL: api/v1
  DEVICE_DATA_INDEX_NAME: device-status-dev*
  DEFINITIONS_GRPC_ADDR: device-definitions-api-dev:8086
  DEVICES_GRPC_ADDR: devices-api-dev:8086
  VEHICLE_DECODING_GRPC_ADDR: vehicle-signal-decoding-dev:8086
  TWILIO_API_URL: https://supersim.twilio.com/v1/Sims/%s
  ENABLE_PERMISSIONS: true
  REDIS_TLS: true
  KAFKA_BROKERS: kafka-dev-dimo-kafka-kafka-brokers:9092
  INTEGRATION_TABLE: table.device.integration.autopi
  INGEST_CONSUMER_GROUP: integration-join-processor
  DEVICE_DATA_GRPC_ADDR: device-data-api-dev:8086
  DIMO_IDENTITY_API: https://identity-api.dev.dimo.zone
service:
  type: ClusterIP
  ports:
    http:
      port: 8080
      targetPort: http
      protocol: TCP
ports:
  - name: http
    containerPort: 8080
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    external-dns.alpha.kubernetes.io/hostname: admin.dev.dimo.zone
  hosts:
    - host: admin.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
