name: buildpushmain
on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: buildpushmain
    runs-on: [ self-hosted, linux ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "BUILD_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/vehicle-info-web:${{ steps.slug.outputs.BUILD_TAG }}, dimozone/vehicle-info-web:latest

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v0.13.2
        with:
          valueFile: 'charts/vehicle-info-web/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.slug.outputs.BUILD_TAG }}
          branch: main
          message: 'Update Image Version to ${{ steps.slug.outputs.BUILD_TAG }}'
